CursosDeProgramacion/Models/Curso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace CursosDeProgramacion.Models
{
    public class Curso
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "El campo {0} es obligatorio")]
        public string Descripcion { get; set; }
        public int? Precio { get; set; }
        public List<Modulo> Modulos { get; set; }


    }
}

CursosDeProgramacion/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CursosDeProgramacion.Data;
using CursosDeProgramacion.Models;

namespace CursosDeProgramacion.Controllers
{
    public class CursosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CursosController(ApplicationDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        // GET: Cursos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Curso.ToListAsync());
        }

        [AllowAnonymous]
        // GET: Cursos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .Include(c => c.Modulos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        [Authorize(Roles = "AdministrativeUser")]
        // GET: Cursos/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "AdministrativeUser")]
        // POST: Cursos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Descripcion,Precio")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _context.Add(curso);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize(Roles = "AdministrativeUser")]
        // GET: Cursos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso.FindAsync(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        [Authorize(Roles = "AdministrativeUser")]
        // POST: Cursos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Descripcion,Precio")] Curso curso)
        {
            if (id != curso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(curso);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize(Roles = "AdministrativeUser")]
        // GET: Cursos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = await _context.Curso
                .FirstOrDefaultAsync(m => m.Id == id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        [Authorize(Roles = "AdministrativeUser")]
        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = await _context.Curso.FindAsync(id);
            _context.Curso.Remove(curso);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _context.Curso.Any(e => e.Id == id);
        }
    }
}

CursosDeProgramacion/Views/Cursos/Create.cshtml
@model CursosDeProgramacion.Models.Curso

@{
    ViewData["Title"] = "Create";
}
@section Styles  {
    <link rel="stylesheet" href="~/css/forms.css" />
}

<section class="section1">
    <div class="content section1Flex">
        <form asp-action="Create">
            <h1>Crear curso:</h1>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label> <br />
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label> <br />
                <textarea asp-for="Descripcion" class="form-control"> </textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label> <br />
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear curso" class="button" />
                <a href="#">Cancelar</a>
            </div>
        </form>
     </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursosDeProgramacion/Views/Cursos/Delete.cshtml
@model CursosDeProgramacion.Models.Curso

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CursosDeProgramacion/Views/Cursos/Details.cshtml
@model CursosDeProgramacion.Models.Curso

@{
    ViewData["Title"] = "Details";
}

@section Styles  {
    <link rel="stylesheet" href="~/css/cursos/details.css" />
}

<section class="section1">
    <div class="content section1Flex">
        <div class="hero">
            <h1>@Html.DisplayFor(model => model.Titulo)</h1>
            <p>@Html.DisplayFor(model => model.Descripcion)</p>
        </div>

        <iframe src="https://player.vimeo.com/video/20534171?title=0&byline=0&portrait=0" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

        <button class="heroButton" onclick="window.location.href='algoritmos.html'"> Continuar Curso</button>
    </div>
</section>

<section class="section2">
    <div class="content section2Flex">
        @foreach (Modulo modulo in @Model.Modulos)
        {
            <div class="priceCard">
                <div class="circle">1</div>
                <span class="planName">@Html.DisplayFor(moduloItem => modulo.Titulo)</span>  <br>
                <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star" style="color: #73CEFF "></i>
                <br>

                <p>@Html.DisplayFor(moduloItem => modulo.Descripcion)</p>
                <hr>
                <a href="#" class="button"> Ver Curso </a>
            </div>
        }
    </div>
</section>

CursosDeProgramacion/Views/Cursos/Edit.cshtml
@model CursosDeProgramacion.Models.Curso

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Curso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CursosDeProgramacion/Views/Cursos/Index.cshtml
@model IEnumerable<CursosDeProgramacion.Models.Curso>

@{
    ViewData["Title"] = "Index";
}
@section Styles  {
    <link rel="stylesheet" href="~/css/cursos/index.css" />
}

<section class="section1">
    <div class="content section1Flex">
        <div class="hero">
            <h1>Cursos de programación:</h1>
            <p>Busca, inscribete y aprende a programar con uno de nuestros cursos disponibles.</p>
        </div>
    </div>
</section>

<section class="section2">
    <div class="content section2Flex">
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        @foreach (var item in Model)
        {
            <div class="priceCard">
                <div class="circle"></div>
                <span class="planName">@Html.DisplayFor(modelItem => item.Titulo)</span>
                <br>
                <br>
                <p>@Html.DisplayFor(modelItem => item.Descripcion)</p>
                <hr>
                <a asp-controller="Cursos" asp-action="Details" asp-route-id="@item.Id" class="button">Ver Mas</a>
            </div>
        }
    </div>
</section>